language: objective-c

install:
  - brew install neko haxe
  - cd ..
  - mkdir haxelib
  - haxelib setup haxelib
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install hxjava
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - haxe test.hxml
