version: "{build}"

clone_folder: C:\projects\haxe-threadpool

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib

install:
    # Install haxe and neko
    - cinst neko -y
    - cinst haxe -y
    - RefreshEnv
    - neko -version
    - haxe -version
    # Setup haxelib
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install record-macros
    - haxelib install hxcpp

build_script:
    - cd test
    - haxe compile.hxml

test_script:
    - echo CPP
    - pwd
    - bin/test/TestMain.exe
    - echo NEKO
    - neko bin/test/TestMain.n
