version: "{build}"

clone_folder: C:\projects\haxe-threadpool

environment:
    global:
        HAXELIB_ROOT: C:\projects\haxelib

install:
    # Install haxe and neko
    - cinst neko -y
    - cinst haxe -y
    - RefreshEnv
    - neko -version
    - haxe -version
    # Setup haxelib
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    - haxelib install record-macros
    - haxelib install hxcpp
    - haxelib install hxcs
    - haxelib install hxjava

build_script:
    - cd test
    - haxe compile.hxml
    - cd ..

test_script:
    - echo CPP
    - bin\test\cpp\TestMain.exe 10
    - echo NEKO
    - neko bin\test\TestMain.n 10
    - echo C#
    - bin\test\cs\bin\TestMain.exe 10
    - echo JAVA
    - java -jar bin\test\java\TestMain.jar 10
    - echo PYTHON
    - python bin\test\TestMain.py 10
